AWSTemplateFormatVersion: 2010-09-09
Description: ECR infrastructure for the notes-api-v2 backend, intended for integration with circleci.
Resources:
  ContainerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: notes-api-v2-ecr
  CircleCiUser:
    Type: AWS::IAM::User
    Properties:
      UserName: circleci_user
      LoginProfile:
        Password: circleci_user
        PasswordResetRequired: True
  CircleCiRepositoryPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - ContainerRepository
      - CircleCiUser
    Properties:
      PolicyName: NotesApiV2EcrAccess
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ecr:*
            Resource: !GetAtt ContainerRepository.Arn
          - Effect: Allow
            Action:
              - ecr:GetAuthorizationToken
            Resource: '*'
      Users:
        - circleci_user
