AWSTemplateFormatVersion: 2010-09-09
Description: Backend infrastructure for the notes-api-v2 backend.
Resources:
  NotesBackendVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

  NotesApiSubnetA:
    Type: AWS::EC2::Subnet
    DependsOn:
      - NotesBackendVpc
    Properties:
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ca-central-1a
      MapPublicIpOnLaunch: false
      VpcId: !Ref NotesBackendVpc

  NotesApiEcrRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: EcsEcrRepositoryPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:BatchGetImage
                  - ecr:GetDownloadUrlForLayer
                  - ecr:GetAuthorizationToken
                Resource: '*'

  NotesApiEcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: notes-api-ecs-cluster

  NotesApiEcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - NotesApiEcrRole
    Properties:
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Image: 844544735981.dkr.ecr.ca-central-1.amazonaws.com/notes-api-v2-ecr:latest #TODO hide acc id / take as param
          Name: notes-api-v2
          Environment:
            - Key: HELLO_WORLD_MODE
              Value: true
      ExecutionRoleArn: !GetAtt NotesApiEcrRole.Arn

  NotesApiEcsService:
    Type: AWS::ECS::Service
    DependsOn:
      - NotesApiSubnetA
      - NotesApiEcsTaskDefinition
    Properties:
      Cluster: !Ref NotesApiEcsCluster
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !Ref NotesApiSubnetA
      SchedulingStrategy: REPLICA
      ServiceName: notes-api-ecs-service
      TaskDefinition: !Ref NotesApiEcsTaskDefinition
