AWSTemplateFormatVersion: 2010-09-09
Description: Backend infrastructure for the notes-api-v2 backend.
Resources:

  ## TODO: parameterize lots of things (DRY); eliminate unnecessary DependsOn; Description and Tags
  ## VPC

  NotesBackendVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  NotesBackendInternetGateway:
    Type: AWS::EC2::InternetGateway

  NotesBackendVpcIgAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn:
      - NotesBackendVpc
      - NotesBackendInternetGateway
    Properties:
      InternetGatewayId: !Ref NotesBackendInternetGateway
      VpcId: !Ref NotesBackendVpc

  NotesBackendPublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all inbound and outbound traffic from the internet
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
      VpcId: !Ref NotesBackendVpc

  NotesBackendPrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: NotesBackendPublicSecurityGroup
    Properties:
      GroupDescription: Allow all inbound and outbound traffic from public subnets
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref NotesBackendPublicSecurityGroup
          IpProtocol: -1
          FromPort: -1
          ToPort: -1
      VpcId: !Ref NotesBackendVpc

  ## Public Subnets

  NotesApiLoadBalancerSubnetA:
    Type: AWS::EC2::Subnet
    DependsOn:
      - NotesBackendVpc
    Properties:
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ca-central-1a
      MapPublicIpOnLaunch: true
      VpcId: !Ref NotesBackendVpc

  NotesApiLoadBalancerSubnetB:
    Type: AWS::EC2::Subnet
    DependsOn:
      - NotesBackendVpc
    Properties:
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: ca-central-1b
      MapPublicIpOnLaunch: true
      VpcId: !Ref NotesBackendVpc

  ## Private Subnets

  NotesApiSubnetA:
    Type: AWS::EC2::Subnet
    DependsOn:
      - NotesBackendVpc
    Properties:
      CidrBlock: 10.0.11.0/24
      AvailabilityZone: ca-central-1a
      MapPublicIpOnLaunch: false
      VpcId: !Ref NotesBackendVpc

  NotesApiSubnetB:
    Type: AWS::EC2::Subnet
    DependsOn:
      - NotesBackendVpc
    Properties:
      CidrBlock: 10.0.22.0/24
      AvailabilityZone: ca-central-1a
      MapPublicIpOnLaunch: false
      VpcId: !Ref NotesBackendVpc

  # Elastic IPs

  NotesApiElasticIpA:
    Type: AWS::EC2::EIP
    DependsOn:
      - NotesBackendVpcIgAttachment
    Properties:
      Domain: vpc

  NotesApiElasticIpB:
    Type: AWS::EC2::EIP
    DependsOn:
      - NotesBackendVpcIgAttachment
    Properties:
      Domain: vpc

  ## Nat Gateways

  NotesApiNatA:
    Type: AWS::EC2::NatGateway
    DependsOn:
      - NotesApiElasticIpA
      - NotesApiLoadBalancerSubnetA
    Properties:
      AllocationId: !GetAtt NotesApiElasticIpA.AllocationId
      SubnetId: !Ref NotesApiLoadBalancerSubnetA

  NotesApiNatB:
    Type: AWS::EC2::NatGateway
    DependsOn:
      - NotesApiElasticIpB
      - NotesApiLoadBalancerSubnetB
    Properties:
      AllocationId: !GetAtt NotesApiElasticIpB.AllocationId
      SubnetId: !Ref NotesApiLoadBalancerSubnetB

  ## Public route tables and routing

  NotesBackendPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref NotesBackendVpc

  NotesBackendDefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn:
      - NotesBackendInternetGateway
    Properties:
      RouteTableId: !Ref NotesBackendPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref NotesBackendInternetGateway

  NotesApiLoadBalancerSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref NotesBackendPublicRouteTable
      SubnetId: !Ref NotesApiLoadBalancerSubnetA

  NotesApiLoadBalancerSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref NotesBackendPublicRouteTable
      SubnetId: !Ref NotesApiLoadBalancerSubnetB

  ## Private route tables and routing

  NotesBackendPrivateRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref NotesBackendVpc

  NotesApiPrivateRouteA:
    Type: AWS::EC2::Route
    DependsOn:
      - NotesBackendInternetGateway
    Properties:
      RouteTableId: !Ref NotesBackendPrivateRouteTableA
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NotesApiNatA

  NotesApiRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref NotesBackendPrivateRouteTableA
      SubnetId: !Ref NotesApiSubnetA

  NotesBackendPrivateRouteTableB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref NotesBackendVpc

  NotesApiPrivateRouteB:
    Type: AWS::EC2::Route
    DependsOn:
      - NotesBackendInternetGateway
    Properties:
      RouteTableId: !Ref NotesBackendPrivateRouteTableB
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NotesApiNatB

  NotesApiRouteTableAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref NotesBackendPrivateRouteTableB
      SubnetId: !Ref NotesApiSubnetB

  ## ECS IAM

  NotesApiEcrRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: EcsEcrRepositoryPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:BatchGetImage
                  - ecr:GetDownloadUrlForLayer
                  - ecr:GetAuthorizationToken
                Resource: '*'

  ## ALB

  NotesApiLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    DependsOn:
      - NotesApiLoadBalancerSubnetA
      - NotesApiLoadBalancerSubnetB
      - NotesBackendVpcIgAttachment
    Properties:
      IpAddressType: ipv4
      Name: notes-api-load-balancer
      Scheme: internet-facing
      Subnets:
        - !Ref NotesApiLoadBalancerSubnetA
        - !Ref NotesApiLoadBalancerSubnetB
      Type: application
      SecurityGroups:
        - !Ref NotesBackendPublicSecurityGroup

  NotesApiLoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn:
      - NotesBackendVpc
      - NotesApiLoadBalancer
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetType: ip
      Name: notes-api-lb-target-group
      Port: 3000
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: !Ref NotesBackendVpc

  NotesApiLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - NotesApiLoadBalancerTargetGroup
      - NotesApiLoadBalancer
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NotesApiLoadBalancerTargetGroup
      LoadBalancerArn: !Ref NotesApiLoadBalancer
      Port: 80
      Protocol: HTTP

  NotesApiLoadBalancerListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DependsOn:
      - NotesApiLoadBalancerTargetGroup
      - NotesApiLoadBalancer
      - NotesApiLoadBalancerListener
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref NotesApiLoadBalancerTargetGroup
      Conditions:
        - Field: path-pattern
          Values:
            - '*'
      ListenerArn: !Ref NotesApiLoadBalancerListener
      Priority: 1

  ## ECS

  NotesApiEcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: notes-api-ecs-cluster

  NotesApiEcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - NotesApiEcrRole
    Properties:
      Cpu: 512
      Memory: 1024
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Image: 844544735981.dkr.ecr.ca-central-1.amazonaws.com/notes-api-v2-ecr:latest #TODO hide acc id / take as param
          Name: notes-api-v2
          PortMappings:
            - ContainerPort: 3000
          Environment:
            - Name: HELLO_WORLD_MODE
              Value: true
      ExecutionRoleArn: !GetAtt NotesApiEcrRole.Arn

  NotesApiEcsService:
    Type: AWS::ECS::Service
    DependsOn:
      - NotesApiSubnetA
      - NotesApiSubnetB
      - NotesApiEcsTaskDefinition
      - NotesApiLoadBalancer
      - NotesApiLoadBalancerTargetGroup
      - NotesApiLoadBalancerListener
    Properties:
      Cluster: !Ref NotesApiEcsCluster
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !Ref NotesApiSubnetA
            - !Ref NotesApiSubnetB
      SchedulingStrategy: REPLICA
      ServiceName: notes-api-ecs-service
      TaskDefinition: !Ref NotesApiEcsTaskDefinition
      LoadBalancers:
        - ContainerName: notes-api-v2
          ContainerPort: 3000
          TargetGroupArn: !Ref NotesApiLoadBalancerTargetGroup
